CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar(20) NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "email" varchar(30) NOT NULL,
  "password" varchar(30) NOT NULL,
  "age" int NOT NULL,
  "role_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(300) NOT NULL,
  "category_id" int NOT NULL
  "level_id" int NOT NULL,
  "teacher" int NOT NULL,
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(100) NOT NULL,
  "url" varchar(100) NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "students_courses" (
  "student" int NOT NULL,
  "course_id" int NOT NULL
);

ALTER TABLE "course_videos" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "users" ("id");

ALTER TABLE "students_courses" ADD FOREIGN KEY ("student") REFERENCES "users" ("id");

ALTER TABLE "students_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id") REFERENCES "levels" ("id");


/* --- INSERTS EN TABLAS --- */


/* --- CATEGORIAS --- */

INSERT INTO categories VALUES ('Administración y negocios');
INSERT INTO categories VALUES ('Comunicación');
INSERT INTO categories VALUES ('Marketing y publicidad');
INSERT INTO categories VALUES ('Sistemas y tecnología');


/* --- ROLES --- */

INSERT INTO roles VALUES ('Administrador');
INSERT INTO roles VALUES ('Profesor');
INSERT INTO roles VALUES ('Estudiante');


/* --- NIVELES --- */

INSERT INTO levels VALUES ('Principiante');
INSERT INTO levels VALUES ('Intermedio');
INSERT INTO levels VALUES ('Experto');


/* --- USUARIOS --- */

INSERT INTO usuarios VALUES ('Axel Rose', 'axlrs@hotmail.com', 'gnr1980', 32, 3);
INSERT INTO usuarios VALUES ('Roger Waters', 'rogerwpf@gmail.com', 'pinkf1960', 43, 1);
INSERT INTO usuarios VALUES ('Mick Jagger', 'mjagger@hotmail.com', '1960rollings', 45, 2);
INSERT INTO usuarios VALUES ('Kurt Kobain', 'kurt@hotmail.com', 'kurtco27', 28, 3);
INSERT INTO usuarios VALUES ('Paul McCartney', 'william_c@hotmail.com', 'beatle1960', 21, 2);
INSERT INTO usuarios VALUES ('Robert Plant', 'rob_plant@hotmail.com', 'ledzepp1970', 30, 3);


/* --- CURSOS --- */

INSERT INTO courses VALUES ('Administración de empresas','Gestiona de forma estratégica las distintas áreas involucradas en un negocio.', 1, 2, 1);
INSERT INTO courses VALUES ('Negocios internacionales','Crea, promueve y gestiona los negocios en el contexto de los mercados globales.', 1, 3, 3);
INSERT INTO courses VALUES ('Comunicación integral','Crea y ejecuta planes según las necesidades de tu audiencia.', 2, 1, 2);
INSERT INTO courses VALUES ('Comunicación audiovisual','Desarrolla y gestionar productos audiovisuales para televisión y plataformas digitales.',2, 1, 2);
INSERT INTO courses VALUES ('Publicidad y medios digitales','Aprende a desarrollar campañas publicitarias estratégicamente en distintos medios digitales.',3, 1, 3);
INSERT INTO courses VALUES ('Gestión comercial y negocios digitales','Analiza las tendencias y ejecuta planes de desarrollo de una empresa, producto o servicio utilizando herramientas digitales.',3, 2, 3);
INSERT INTO courses VALUES ('Desarrollo de software', 'Diseña, desarrolla y aplica soluciones informáticas sobre aplicaciones de software nuevas y/o existentes.', 4, 3, 4);
INSERT INTO courses VALUES ('Redes y comunicaciones', 'Analizar, diseña e implementa soluciones seguras sobre infraestructura tecnológica nueva o existente.', 4, 3, 4);


/* --- VIDEOS --- */

INSERT INTO course_videos VALUES ('Gestión estratégica de negocios', 'https://us02web.zoom.us/rec/share/73g3rSReDsgsfaesam', 1);
INSERT INTO course_videos VALUES ('Introducción a negocios locales', 'https://us02web.zoom.us/rec/share/84WR3SReD6gX2amzGm', 2);
INSERT INTO course_videos VALUES ('Comunicación corporativa', 'https://us02web.zoom.us/rec/share/92hQ1SReD6gX2zGmam,', 3);
INSERT INTO course_videos VALUES ('Herramientas digitales', ' https://us02web.zoom.us/rec/share/10rjsefmnJNReD6gX2', 4);
INSERT INTO course_videos VALUES ('Creatividad y proyectos', 'https://us02web.zoom.us/rec/share/34kJjkdjsio4p3dwF4', 5);
INSERT INTO course_videos VALUES ('Fundamentos de la publicidad', 'https://us02web.zoom.us/rec/share/89jnwfnwikwfbn3wi3', 6);
INSERT INTO course_videos VALUES ('Diseño de bases de datos', 'https://us02web.zoom.us/rec/share/76hjdklwshbNkdssO4', 7);
INSERT INTO course_videos VALUES ('Seguridad de la infraestructura de TI', 'https://us02web.zoom.us/rec/share/25jfhndnJKnfweJ46g"', 8);


/* --- CURSOS DE ESTUDIANTES --- */

INSERT INTO students_courses VALUES (6, 2);
INSERT INTO students_courses VALUES (4, 4);
INSERT INTO students_courses VALUES (1, 7);